### ISSUE TITLE
[Feat] 마이페이지 API 연결

### ISSUE THREAD

**Issue by chayoosang** [MyChore/MyChore-IOS#12]
# 📝 작업 목적
마이페이지 API 연결

# 🛠️ Tasks
- [ ] 로그아웃
- [ ] 회원탈퇴
- [ ] 내 정보 수정
- [ ] 프로필 사진 수정
- [ ] 프로필 사진 삭제
- [ ] 프로필 조회
- [ ] 알림 설정 수정
