### ISSUE TITLE
[Feat] HomeView UI 구현

### ISSUE THREAD

**Issue by soletree** [MyChore/MyChore-IOS#14]
# 📝 작업 목적
- 평면도를 제외한 홈 뷰의 UI를 구현합니다. 

# 🛠️ Tasks
- [ ] 집안일 목록 구현
- [ ] 집안일 완료 ProgressView 구현
- [ ] todo list 구현
