### ISSUE TITLE
[Add/Test] 데모데이용 이미지 에셋 추가 및 알럿 추가

### ISSUE THREAD

**Issue by soletree** [MyChore/MyChore-IOS#41]
# 📝 작업 목적
- 데모데이용 이미지 에셋을 추가합니다. 
- 데모데이용 텍스트 입력 알럿을 추가합니다. 

# 🛠️ Tasks
- [x] 평면도 이름 수정 알럿 추가
- [x] 그룹 이름 수정 알럿 추가
- [x] 평면도 이미지 추가
